apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/AGBS074/yaml-devops-practice.git
    path: kubernetes
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
